---
- name: Install Chocolatey
  hosts: windows-virt-host

  tasks:
    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
   - name: Install 7-zip
     win_shell: |
        choco install 7zip.install -y --force
   - name: Install MultiCommander
     win_shell: |
       choco install multicommander
   - name: Install TeamViewer8
     win_shell: |
       choco install teamviewer8 
